Repository googleapis/google-cloudevents-python, pull requests merged in 2021-04, with the labels that each got.

#44 chore: Add license headers for python config files
  docs/conf.py
  synth.metadata
Labels: api: eventarc, automerge, cla: yes, context: full

#46 chore: prevent normalization of semver versioning
  setup.py
Labels: api: eventarc, cla: yes

#47 chore(revert): revert preventing normalization
  setup.py
Labels: api: eventarc, cla: yes

#45 chore: add constraints file check for python samples
  renovate.json
  synth.metadata
Labels: api: eventarc, automerge, cla: yes, context: full, samples
