Repository googleapis/google-cloudevents-python, pull requests merged in 2021-02, with the labels that each got.

#29 fix(packaging): python module structure and dependencies
  README.md
  gen/src/index.ts
  gen/templates/README.squirrelly
  gen/templates/setup_py.squirrelly
  requirements-dev.txt
  requirements.txt
  setup.py
  src/google/__init__.py
  src/google/events/__init__.py
  src/google/events/cloud/__init__.py
  src/google/events/cloud/audit/__init__.py
  src/google/events/cloud/cloudbuild/__init__.py
  src/google/events/cloud/firestore/__init__.py
  src/google/events/cloud/pubsub/__init__.py
  src/google/events/cloud/scheduler/__init__.py
  src/google/events/cloud/storage/__init__.py
  src/google/events/firebase/__init__.py
  src/google/events/firebase/analytics/__init__.py
  src/google/events/firebase/auth/__init__.py
  src/google/events/firebase/database/__init__.py
  src/google/events/firebase/remoteconfig/__init__.py
Labels: api: eventarc, automerge, cla: yes

#19 chore: start tracking obsolete files
  synth.metadata
Labels: api: eventarc, automerge, cla: yes, context: full

#22 chore(python): fix column sizing issue in docs
  docs/_static/custom.css
  synth.metadata
Labels: api: eventarc, automerge, cla: yes, context: full

#35 [CHANGE ME] Re-generated to pick up changes from self.
  .kokoro/test-samples.sh
  .kokoro/trampoline_v2.sh
Labels: api: eventarc, automerge, cla: yes, context: none

#38 docs: add pypi badge
  README.md
Labels: api: eventarc, automerge, cla: yes

#41 [CHANGE ME] Re-generated to pick up changes from synthtool.
  .kokoro/build.sh
  .kokoro/docs/docs-presubmit.cfg
  .kokoro/test-samples.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  MANIFEST.in
  synth.metadata
Labels: api: eventarc, automerge, cla: yes, context: full
